name: Release to Maven Central Repository
on:
    push:
        tags:
            - '*'
jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up Maven Central Repository
              uses: actions/setup-java@v3
              with:
                java-version: 17
                distribution: 'temurin'
                cache: 'maven'

            - name: Build, test, verify
              run: mvn -B verify
            - name: Check POM metadata for release
              run: mvn pomchecker:check-maven-central

            # Running setup-java again overwrites the settings.xml - IT'S MANDATORY TO DO THIS SECOND SETUP!!!
            - name: Set up Maven Central Repository
              uses: actions/setup-java@v3
              with:
                  java-version: 17
                  distribution: 'temurin'
                  cache: 'maven'
                  server-id: ossrh
                  server-username: MAVEN_USERNAME
                  server-password: MAVEN_PASSWORD
                  gpg-private-key: ${{ secrets.MAVEN_GPG_KEY }}
                  gpg-passphrase: MAVEN_GPG_PASSPHRASE
            - name: Sign + Publish release
              run: mvn -Prelease deploy -DskipTests
              env:
                  MAVEN_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
                  MAVEN_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
                  MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}